### PR TITLE
Issue: Removal of IRC hooks

### PR DESCRIPTION
**Pull request by MrBitKoin**
-Removed the IRC source files
-Updated Qt Creator project to not include irc source.
-Removed command line test for -irc

### CODE REVIEW

**Comment by nisanb** [comment]
Did you also remove all dependencies from other sources?
example: net.cpp, line 1678 -
`threadGroup.create_thread(boost::bind(&TraceThread<void (*)()>, "irc", &ThreadIRCSeed));`

**Comment by MrBitKoin** [comment]
Forgot to add the file from the stage. Either way I had forgotten to comment out the #include "irc.h" so was good I had to go back and look. Thank you.

**Comment by nisanb** [comment]
Awesome. Did you compile to check there are no other dependencies included?

**Comment by nisanb** [comment]
Hi. I've added the code changes required for the IRC deprecation at pull request #25 
Please close this pull request as it is a duplicate

**Pull request closed without merging**
