### PR TITLE
Create test.txt

### PR DESCRIPTION
**Pull request by J-SDII**
test

### CODE REVIEW

**Comment by Gtibroeder** [comment]
Is this project still alive?

**Comment by J-SDII** [comment]
I dont think so, was trying to test to make sure it wasnt a public repository before I told the new "team" to add a .txt file to the github proving they own it. I dont think they do, but we will see.

**Comment by Gtibroeder** [comment]
Yeah i already thought project is death but we wil see

**Comment by tchernienko** [comment]
same here. 7 months inactive... there are so many dead coin projects... any one know of a web site or blog listing these corpse?

**Comment by nisanb** [comment]
Please close this pull request.

**Pull request closed without merging**
